'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { Home, List, CalendarDays, ChartNoAxesCombined, MapPin, Fish, LogOut, Plus } from 'lucide-react';
import { useData } from '@/lib/store';
const nav = [{ href: '/', label: 'ホーム', icon: Home }, { href: '/catches', label: '釣果', icon: List }, { href: '/calendar', label: 'カレンダー', icon: CalendarDays }, { href: '/analysis', label: '分析', icon: ChartNoAxesCombined }, { href: '/spots', label: '釣り場', icon: MapPin }];
export function Shell({ children }: { children: React.ReactNode }) {
  const path = usePathname(); const router = useRouter(); const { demo, signOut, error } = useData();
  return <div className="app-shell"><aside className="sidebar"><Link className="logo" href="/"><span className="logo-icon"><Fish size={25}/></span><span>FISH<span className="accent">LOG</span><small>釣れた瞬間を、データにする。</small></span></Link><div className="side-nav">{nav.map(item => <Link key={item.href} href={item.href} className={`nav-item ${path === item.href ? 'active' : ''}`}><item.icon size={19}/>{item.label}</Link>)}</div><Link href="/sessions" className={`nav-item ${path === '/sessions' ? 'active' : ''}`}><span className="session-icon">◷</span>釣行セッション</Link><div className="side-bottom">{demo && <div className="demo-badge">デモモード<br/><small>データはこの端末だけに保存</small></div>}{!demo && <button className="quiet-button" onClick={async () => { await signOut(); router.push('/'); }}><LogOut size={17}/>ログアウト</button>}</div></aside><div className="main-wrap"><header className="topbar"><Link className="mobile-logo" href="/"><Fish size={23}/> FISH<span>LOG</span></Link><span className="topbar-tag">PRIVATE FISHING JOURNAL</span><Link className="topbar-action" href="/catch/new" onClick={() => sessionStorage.setItem('fish-log-caught-at', new Date().toISOString())}><Plus size={18}/>釣果を記録</Link></header>{demo && <div className="demo-strip">デモモード · 入力内容はこのブラウザ内に保存されます。Supabase接続後は実データを利用できます。</div>}{error && <div className="error-strip">データを読み込めません: {error}</div>}<main className="content">{children}</main><nav className="bottom-nav">{nav.slice(0,2).map(item => <Link key={item.href} href={item.href} className={path === item.href ? 'active' : ''}><item.icon size={22}/><span>{item.label}</span></Link>)}<Link href="/catch/new" onClick={() => sessionStorage.setItem('fish-log-caught-at', new Date().toISOString())} className="catch-tab" aria-label="釣れた！"><Plus size={28}/></Link>{nav.slice(2,4).map(item => <Link key={item.href} href={item.href} className={path === item.href ? 'active' : ''}><item.icon size={22}/><span>{item.label}</span></Link>)}</nav></div></div>;
}
