'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Camera, Check, Clock3, MapPin, Moon, Waves, CloudSun } from 'lucide-react';
import Link from 'next/link';
import { useData } from '@/lib/store';
import { getPosition, matchSpot } from '@/lib/geo';
import { moonAt } from '@/lib/moon';
import { jmaTide, openMeteoWeather } from '@/lib/providers';
import type { Coordinates, Snapshot } from '@/lib/types';
import { dateTime } from '@/components/format';
export default function NewCatch() {
  const router = useRouter(); const { data, saveCatch } = useData();
  const [caughtAt, setCaughtAt] = useState(() => new Date().toISOString());
  const [ready, setReady] = useState(false); const [species, setSpecies] = useState(''); const [length, setLength] = useState(''); const [weight, setWeight] = useState(''); const [count, setCount] = useState('1'); const [spotId, setSpotId] = useState(''); const [sessionId, setSessionId] = useState(''); const [note, setNote] = useState(''); const [photo, setPhoto] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null); const [location, setLocation] = useState<Coordinates | null>(null); const [locStatus, setLocStatus] = useState('位置情報を確認中…'); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { const timestamp = sessionStorage.getItem('fish-log-caught-at'); if (timestamp) { queueMicrotask(() => setCaughtAt(timestamp)); sessionStorage.removeItem('fish-log-caught-at'); } queueMicrotask(() => setReady(true)); getPosition().then(point => { setLocation(point); const spot = matchSpot(point, data.spots); if (spot) setSpotId(spot.id); setLocStatus(spot ? `${spot.name} を検出` : '現在地を取得しました'); }).catch(() => setLocStatus('位置情報を取得できませんでした')); }, [data.spots]);
  async function submit(e: React.FormEvent) { e.preventDefault(); if (saving) return; setSaving(true); setError(''); const at = new Date(caughtAt); let point = location; if (!point) { try { point = await getPosition(3500); } catch { /* optional */ } } const matched = point ? matchSpot(point, data.spots) : null; const selected = data.spots.find(s => s.id === spotId) || matched; const environmentPoint = point || (selected ? { latitude: selected.latitude, longitude: selected.longitude } : null); const warnings: string[] = []; const [weatherResult, tideResult] = await Promise.allSettled(environmentPoint ? [openMeteoWeather.get(environmentPoint, at), jmaTide.get(environmentPoint, at)] : [Promise.reject('no location'), Promise.reject('no location')]); const weather = weatherResult.status === 'fulfilled' ? weatherResult.value : null; const tide = tideResult.status === 'fulfilled' ? tideResult.value : null; if (!point) warnings.push('位置情報を取得できませんでした'); if (environmentPoint && !weather) warnings.push('天気を取得できませんでした'); if (environmentPoint && (!tide || tide.height_cm == null)) warnings.push('潮位を取得できませんでした'); const snapshot: Snapshot = { coordinates: point, spot_name: selected?.name || null, weather, tide, moon: moonAt(at), collected_at: new Date().toISOString(), warnings }; try { await saveCatch({ id: crypto.randomUUID(), caught_at: at.toISOString(), created_at: new Date().toISOString(), species: species.trim() || '魚種未入力', length_cm: length ? Number(length) : null, weight_g: weight ? Number(weight) : null, count: Math.max(1, Number(count) || 1), spot_id: selected?.id || null, session_id: sessionId || null, note: note.trim(), photo_path: null, snapshot }, photo); router.push('/catches'); } catch (err) { setError(err instanceof Error ? err.message : '保存できませんでした'); setSaving(false); } }
  return <div className="form-page"><Link className="back-link" href="/"><ArrowLeft size={17}/>ホームに戻る</Link><div className="page-kicker">NEW CATCH <span>— 釣果登録</span></div><div className="form-header"><div><h1>釣れた！</h1><p>この瞬間の記録を残しましょう。</p></div><div className="caught-time"><Clock3 size={19}/><div><small>釣れた時刻</small><strong>{ready ? dateTime(caughtAt) : '確認中…'}</strong></div><Check size={17}/></div></div><form onSubmit={submit} className="form-layout"><div className="form-main"><div className="panel form-panel"><div className="section-head"><div><span className="eyebrow">THE CATCH</span><h2>釣果情報</h2></div></div><div className="field"><label htmlFor="species">魚種</label><input id="species" value={species} onChange={e => setSpecies(e.target.value)} placeholder="例：シーバス、アジ、ヒラメ"/></div><div className="field-grid"><div className="field"><label htmlFor="length">全長 <small>cm</small></label><input id="length" type="number" min="0" step="0.1" inputMode="decimal" value={length} onChange={e => setLength(e.target.value)} placeholder="例：45.5"/></div><div className="field"><label htmlFor="weight">重さ <small>g</small></label><input id="weight" type="number" min="0" step="1" inputMode="numeric" value={weight} onChange={e => setWeight(e.target.value)} placeholder="例：1200"/></div><div className="field"><label htmlFor="count">匹数</label><input id="count" type="number" min="1" step="1" inputMode="numeric" value={count} onChange={e => setCount(e.target.value)}/></div></div><div className="field"><label htmlFor="note">メモ</label><textarea id="note" value={note} onChange={e => setNote(e.target.value)} placeholder="ルアー、仕掛け、その時の様子など" rows={4}/></div></div><div className="panel form-panel"><div className="section-head"><div><span className="eyebrow">MOMENT</span><h2>写真</h2></div></div><label className="upload-box" htmlFor="photo">{preview ? /* eslint-disable-next-line @next/next/no-img-element */
<img src={preview} alt="選択した写真"/> : <><Camera size={30}/><strong>写真を追加</strong><small>タップして撮影・選択</small></>}</label><input id="photo" className="sr-only" type="file" accept="image/*" capture="environment" onChange={e => { const file = e.target.files?.[0] || null; setPhoto(file); if (file) setPreview(URL.createObjectURL(file)); }}/></div></div><aside className="form-aside"><div className="panel form-panel"><div className="section-head"><div><span className="eyebrow">LOCATION</span><h2>釣り場</h2></div></div><p className="location-status"><MapPin size={16}/>{locStatus}</p><div className="field"><label htmlFor="spot">登録済みの釣り場</label><select id="spot" value={spotId} onChange={e => setSpotId(e.target.value)}><option value="">指定なし</option>{data.spots.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></div><div className="field"><label htmlFor="session">釣行セッション</label><select id="session" value={sessionId} onChange={e => setSessionId(e.target.value)}><option value="">指定なし</option>{data.sessions.filter(s => !s.ended_at).map(s => <option value={s.id} key={s.id}>{s.title}</option>)}</select></div><Link className="inline-link" href="/spots">釣り場を管理する →</Link></div><div className="panel auto-panel"><span className="eyebrow">AUTO SNAPSHOT</span><h3>自動で記録</h3><p>保存時に取得できた情報を記録します。</p><div><MapPin size={17}/> GPS と釣り場</div><div><Waves size={17}/> 最寄り気象庁地点の潮汐</div><div><Moon size={17}/> 月齢・月相・照度</div><div><CloudSun size={17}/> 天気・気温・風・気圧</div><small>取得に失敗しても釣果は保存できます。</small></div><button className="primary-button save-button" disabled={saving} type="submit">{saving ? '保存中…' : 'この釣果を保存する'} <Check size={18}/></button>{error && <p className="error-text" role="alert">{error}</p>}</aside></form></div>;
}
